import { Poppins } from "next/font/google";
import "./globals.css";
import { TodoProvider } from '@/context/todo.context'

const poppins = Poppins({weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ["latin"] });

export const metadata = {
  title: "Test for Horizen",
  description: "Generated by my with next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <TodoProvider>{children}</TodoProvider></body>
    </html>
  );
}
