services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "3001:3001"
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "3000:3000"
    restart: always

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
